spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate
            use-new-id-generator-mappings: true
        properties:
            hibernate:
    datasource:
        platform: postgres
        url: jdbc:postgresql://localhost:5432/demo-db?currentSchema=public
        username: admin
        password: admin
        driver-class-name: org.postgresql.Driver
